### ISSUE TITLE
Way support

### ISSUE THREAD

**Issue by jpds** [midzer/doenieren#1]
The map doesn't seem to take into account places that are ways, not nodes, for instance:

- https://www.openstreetmap.org/way/113310931

**Comment by midzer** [comment]
@jpds Good catch! Preprocessing has to consider ways, too https://github.com/midzer/pbf2md/blob/2e5f2de126ef53eadbf44a29ec05d089a88fbc9b/pbf2md.go#L150

same it is done for https://github.com/lokal-ninja project https://github.com/midzer/pbf2md/blob/7ea68380de956eb1b7f395c25d31f0d502d0aebd/pbf2md.go#L641

**Comment by midzer** [comment]
Done via https://github.com/midzer/pbf2md/commit/1ac39d3c8ea664b4cb1329f4193829538948c196

@jpds please check https://doenieren.in/ if everything works for you :)

**Comment by jpds** [comment]
This also looks great, thank you!
