### ISSUE TITLE
Document how nodes are added

### ISSUE THREAD

**Issue by jpds** [midzer/doenieren#2]
I'd like to have this node added to the map: https://www.openstreetmap.org/node/5702482205

But there's no documentation on how to do this/which OSM tags are needed for a node to be considered.

**Comment by midzer** [comment]
@jpds You're absolutely right. This repo lacks a proper `README.md`. I am going to write one the next days.

**Comment by midzer** [comment]
Done via https://github.com/midzer/doenieren/commit/53851e21208703a16754b8b57aa1313e7ed0ff18

@jpds Is this looking good for you?

**Comment by jpds** [comment]
Amazing :+1:
