### ISSUE TITLE
`cuisine` should be allowed to be a `;` separated list

### ISSUE THREAD

**Issue by erictapen** [midzer/doenieren#3]
Just stumbled on this great project.

The [cuisine](https://wiki.openstreetmap.org/wiki/Key:cuisine) key is allowed to have multiple values as a semicolon separated list. The current implementation does only seem to match for exact strings.

Take my favourite döner imbiss for example, which is not shown on the map and has `cuisine=turkish; kebab; burger`:

https://www.openstreetmap.org/node/4560044481

**Comment by midzer** [comment]
Hi @erictapen 

and thanks for opening this issue!

Give me a minute and I fix this here https://github.com/midzer/pbf2md/blob/0d8709e006f95fd091917f58b57d234a7ceeb60a/pbf2md.go#L174

**Comment by midzer** [comment]
Bug fixed and site updated, awesome!
